version: '3.9'

services:
  postgres-attendance:
    image: postgres:16
    container_name: postgres-attendance
    restart: always

    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_password

    ports:
      - "55432:5432"

    volumes:
      - postgres_attendance_data:/var/lib/postgresql/data

  pgadmin-attendance:
    image: dpage/pgadmin4
    container_name: pgadmin-attendance
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@attendance.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "58080:80"

    volumes:
      - pgadmin_attendance_data:/var/lib/pgadmin

    depends_on:
      - postgres-attendance

volumes:
  postgres_attendance_data:
  pgadmin_attendance_data: